module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      margin: {
        small: '10px',
      },
      borderRadius: {
        cards: '20px',
      },
      letterSpacing: {
        logo: '3px',
        nav: '2.5px',
      },
      fontSize: {
        banner: '60px',
        businessTitle: '30px',
        button: '17px',
        contact: '16px',
        dateDay: '40px',
        dateMon: '18px',
        eventDesc: '15px',
        eventMeta: '18px',
        eventTitle: '30px',
        eventTypeBody: '15px',
        eventTypeHeading: '60px',
        featBody: '18px',
        featHeading: '30px',
        footer: '14px',
        formHeading: '30px',
        iconHeading: '25px',
        logoBold: '14px',
        logo: '14px',
        navItem: '12px',
        sectionHeading: '45px',
        tileHeading: '30px',
      },
      width: {
        90: '90%',
      },
      height: {
        90: '90%',
        video: '100%',
      },
      minWidth: {
        menuItem: '104px',
      },
      maxWidth: {
        xs: '360px',
        sm: '480px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        xxl: '1348px',
        businessCard: '566px',
        date: '96px',
        event: '566px',
        featImage: '425px',
        featList: '594px',
        form: '690px',
        map: '586px',
        tile: '350px',
      },
      screens: {
        xs: '360px',
        sm: '480px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        xxl: '1348px',
      },
      padding: {
        wrap: '0 40px',
        logoBanner: '173px',
        wrapMobile: '0 20px',
        video: '56.25%',
      },
      colors: {
        transparent: 'rgba(0,0,0,0)',
        overlay: 'rgba(0,0,0,0.5)',
        white: '#ffffff',
        black: '#1A4059',
        gradBase: '#095495',
        color1: '#EE6E24',
        color2: '#F0874C',
        color3: '#F19C1B',
        color4: '#F5C00E',
        color5: '#C8D92B',
        color5: '#A5CD39',
        color6: '#6ACBE1',
        color7: '#45B1C9',
        color8: '#aa88bf',
      },
      fontFamily: {
        display: ['GP Black'],
        bold: ['GP Bold'],
        semibold: ['GP Semi'],
        medium: ['GP Med'],
        black: ['GP Black'],
        body: ['GP Med'],
      },
    },
  },
  plugins: [],
};
