module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      margin: {
        five: '5px',
        ten: '10px',
        fifteen: '15px',
        twenty: '20px',
        twentyFive: '25px',
        thirty: '30px',
        thirtyFive: '35px',
        forty: '40px',
        fortyFive: '45px',
        navItem: '11px',
      },
      borderRadius: {
        cards: '20px',
      },
      letterSpacing: {
        logo: '3px',
        nav: '2.5px',
        featureHeading: '2.2px',
        eventTypeHeading: '5.2px',
        sectionHeading: '3.5px',
        tile: '2.5px',
      },
      fontSize: {
        banner: '60px',
        businessTitle: '30px',
        button: '17px',
        contact: '16px',
        dateDay: '40px',
        dateMon: '18px',
        eventDesc: '15px',
        eventMeta: '18px',
        eventTitle: '30px',
        eventTypeBody: '15px',
        eventTypeHeading: '60px',
        featBody: '18px',
        featHeading: '30px',
        footer: '14px',
        formHeading: '30px',
        iconHeading: '25px',
        logoBold: '14px',
        logo: '14px',
        navItem: '12px',
        sectionHeading: '45px',
        tileHeading: '30px',
      },
      width: {
        90: '90%',
      },
      height: {
        90: '90%',
        video: '100%',
      },
      minWidth: {
        menuItem: '103px',
      },
      lineHeight: {
        base: '1',
        featBody: '1.67',
      },
      maxWidth: {
        xs: '360px',
        sm: '480px',
        md: '768px',
        xmd: '860px',
        lg: '1024px',
        wlg: '1064px',
        sxl: '1150px',
        xl: '1280px',
        xxl: '1348px',
        mega: '2400px',
        eventTypeHeading: '280px',
        businessCard: '566px',
        date: '96px',
        event: '566px',
        featImage: '425px',
        featList: '594px',
        form: '690px',
        map: '586px',
        tile: '350px',
      },
      screens: {
        xs: '360px',
        sm: '480px',
        md: '768px',
        xmd: '860px',
        lg: '1024px',
        wlg: '1064px',
        sxl: '1150px',
        xl: '1280px',
        xxl: '1348px',
        mega: '2400px',
      },
      padding: {
        wrap: '0 40px',
        logoBanner: '173px',
        wrapMobile: '0 50px',
        video: '56.25%',
        headerHeight: '95px',
        five: '5px',
        ten: '10px',
        fifteen: '15px',
        twenty: '20px',
        twentyFive: '25px',
        thirty: '30px',
        thirtyFive: '35px',
        forty: '40px',
        fortyFive: '45px',
        eventList: '93px 20px 93px 73px',
        eventListMobile: '63px 20px 63px 43px',
        sectionPadding: '93px',
        sectionPaddingBottom: '120px',
      },
      colors: {
        transparent: 'rgba(0,0,0,0)',
        overlay: 'rgba(0,0,0,0.5)',
        white: '#ffffff',
        black: '#1A4059',
        red: '#f26e24',
        color1: '#EE6E24',
        color2: '#F0874C',
        color3: '#F19C1B',
        orange: '#f89c26',
        color4: '#F5C00E',
        yellow: '#ffc10e',
        color5: '#C8D92B',
        color6: '#A5CD39',
        color7: '#6ACBE1',
        color8: '#45B1C9',
        blue: '#2eb1c9',
        gradBase: '#38a1de',
        color9: '#aa88bf',
      },
      fontFamily: {
        display: ['GP Black'],
        bold: ['GP Bold'],
        semibold: ['GP Semi'],
        medium: ['GP Med'],
        black: ['GP Black'],
        body: ['GP Med'],
      },
    },
  },
  plugins: [],
};
