import createSchema from 'part:@sanity/base/schema-creator';
import schemaTypes from 'all:part:@sanity/base/schema-type';
import { heroBanner } from './components';
import { buttons } from './modules';

import {
  aboutPage,
  artsPage,
  blogCategory,
  business,
  businessCategory,
  businessesPage,
  contactInfo,
  contactPage,
  event,
  eventsPage,
  feature,
  globalSettings,
  hcadaPage,
  headingBlock,
  homePage,
  iconItem,
  navMenu,
  person,
  post,
  project,
  projectCategory,
  social,
  svg,
  testimonial,
  volunteerPage,
} from './doctypes';

export default createSchema({
  name: 'default',
  types: schemaTypes.concat([
    aboutPage,
    artsPage,
    blogCategory,
    business,
    businessCategory,
    businessesPage,
    buttons,
    contactInfo,
    contactPage,
    event,
    eventsPage,
    feature,
    globalSettings,
    hcadaPage,
    headingBlock,
    heroBanner,
    homePage,
    iconItem,
    navMenu,
    person,
    post,
    project,
    projectCategory,
    social,
    svg,
    testimonial,
    volunteerPage,
  ]),
});
