export const schedule = [
  {
    date: '07/09/2023',
    day: 'U',
    league: 'ALL',
    notes: 'ALL STAR SUNDAY!!!',
    games: [
      { label: 'AA ALL STAR', time: '5:15 PM' },
      { label: 'AAA ALL STAR', time: '6:00 PM' },
      { label: 'HOME RUN DERBY', time: '6:45 PM' },
      { label: 'MLB ALL STAR (6 innings)', time: '7:30 PM' },
    ],
  },
  {
    date: '07/10/2023',
    day: 'M',
    league: 'AA',
    notes: 'WEEK 3',
    games: [
      { label: 'Golden Door @ Rick Winters', time: '5:15 PM' },
      { label: 'Fidels @ Republic Services', time: '6:00 PM' },
      { label: 'Butcher Shoppe @ Clover Club', time: '6:45 PM' },
      { label: 'Kennys @ Roca Bar', time: '7:30 PM' },
    ],
  },
  {
    date: '07/11/2023',
    day: 'T',
    league: 'MLB',
    notes: 'WEEK 8',
    games: [
      { label: 'WORKING @ SAUCED', time: '5:15 PM' },
      { label: 'DOCS @ EPO', time: '6:00 PM' },
      { label: 'JSPH @ KIPPLEES', time: '6:45 PM' },
      { label: 'HOOD RATS @ MAGIC JOHNSONS', time: '7:30 PM' },
    ],
  },
  {
    date: '07/17/2023',
    day: 'M',
    league: 'AAA',
    notes: 'WEEK 7',
    games: [
      { label: "Esther's Styles @ Stage Two", time: '5:15 PM' },
      { label: 'River City @ Waylons', time: '6:00 PM' },
      { label: 'Deuces @ Lucky Lady', time: '6:45 PM' },
      { label: 'Baseline @ Penny Lane', time: '7:30 PM' },
    ],
  },
  {
    date: '07/18/2023',
    day: 'T',
    league: 'ALL',
    notes: 'FIELD TRIP',
    games: [
      { label: '', time: '5:15 PM' },
      { label: '', time: '6:00 PM' },
      { label: '', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '07/24/2023',
    day: 'M',
    league: 'AAA',
    notes: 'WEEK 8',
    games: [
      { label: 'Waylons @ Baseline', time: '5:15 PM' },
      { label: "Esther's @ Penny Lane", time: '6:00 PM' },
      { label: 'Hartigans @ Stage Two', time: '6:45 PM' },
      { label: 'Schymiks @ Deuces', time: '7:30 PM' },
    ],
  },
  {
    date: '07/25/2023',
    day: 'T',
    league: 'MLB',
    notes: 'WEEK 9',
    games: [
      { label: 'SAUCED @ ORIGINALS', time: '5:15 PM' },
      { label: 'EPO @ 711', time: '6:00 PM' },
      { label: 'KIPPLEES @ AAA', time: '6:45 PM' },
      { label: 'BREWVO @ WORKING', time: '7:30 PM' },
    ],
  },
  {
    date: '07/31/2023',
    day: 'M',
    league: 'AA',
    notes: 'WEEK 4',
    games: [
      { label: 'Butcher Shoppe @ Roca Bar', time: '5:15 PM' },
      { label: 'Fidels @ High Score', time: '6:00 PM' },
      { label: 'Republic Services @ Rick Winters', time: '6:45 PM' },
      { label: 'Clover Club @ Kennys', time: '7:30 PM' },
    ],
  },
  {
    date: '08/01/2023',
    day: 'T',
    league: 'OFF',
    notes: 'RAIN OUT WEEK',
    games: [
      { label: '', time: '5:15 PM' },
      { label: '', time: '6:00 PM' },
      { label: '', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '08/06/2023',
    day: 'U',
    league: 'AA',
    notes: 'SUNDAY SPECIAL WEEK 5',
    games: [
      { label: 'Kennys @ Republic Services', time: '5:15 PM' },
      { label: 'Rick Winters @ Fidels', time: '6:00 PM' },
      { label: 'Golden Door @ Butcher Shoppe', time: '6:45 PM' },
      { label: 'Roca Bar @ Clover Club', time: '7:30 PM' },
    ],
  },
  {
    date: '08/07/2023',
    day: 'M',
    league: 'AAA',
    notes: 'WEEK 9',
    games: [
      { label: 'Pangrea @ Waylons', time: '5:15 PM' },
      { label: 'Baseline @ Esthers', time: '6:00 PM' },
      { label: 'Stage Two @ Penny Lane', time: '6:45 PM' },
      { label: 'Lucky Lady @ Solaris', time: '7:30 PM' },
    ],
  },
  {
    date: '08/08/2023',
    day: 'T',
    league: 'MLB',
    notes: 'WEEK 10',
    games: [
      { label: 'LEROYS @ AAA', time: '5:15 PM' },
      { label: 'WORKING @ MAGIC JOHNSONS', time: '6:00 PM' },
      { label: 'DOCS @ JSPH', time: '6:45 PM' },
      { label: 'HOOD RATS @ SAUCED', time: '7:30 PM' },
    ],
  },
  {
    date: '08/103/2023',
    day: 'U',
    league: 'AA',
    notes: 'SUNDAY SPECIAL WEEK 6',
    games: [
      { label: 'Fidels @ Kennys', time: '5:15 PM' },
      { label: 'Clover Club @ Golden Door', time: '6:00 PM' },
      { label: 'Butcher Shoppe @ Rick Winters', time: '6:45 PM' },
      { label: 'Republic Services @ Roca Bar', time: '7:30 PM' },
    ],
  },
  {
    date: '08/104/2023',
    day: 'M',
    league: 'AAA',
    notes: 'WEEK 10',
    games: [
      { label: 'Penny Lane @ River City', time: '5:15 PM' },
      { label: 'Waylons @ Pangea', time: '6:00 PM' },
      { label: 'Hatigans @ Esthers', time: '6:45 PM' },
      { label: 'Deuces @ Stage Two', time: '7:30 PM' },
    ],
  },
  {
    date: '08/105/2023',
    day: 'T',
    league: 'MLB',
    notes: 'WEEK 11',
    games: [
      { label: 'AAA @ JSPH', time: '5:15 PM' },
      { label: '711 @ LEROYS', time: '6:00 PM' },
      { label: 'MAGIC JOHNSONS @ ORIGINALS', time: '6:45 PM' },
      { label: 'BOKEH @ HOOD RATS', time: '7:30 PM' },
    ],
  },
  {
    date: '08/201/2023',
    day: 'M',
    league: 'AAA',
    notes: 'WEEK 11',
    games: [
      { label: 'River City @ Solaris', time: '5:15 PM' },
      { label: 'Lucky Lady @ Schymiks', time: '6:00 PM' },
      { label: 'Baseline @ Stage Two', time: '6:45 PM' },
      { label: 'Pangea @ Hartigans', time: '7:30 PM' },
    ],
  },
  {
    date: '08/202/2023',
    day: 'T',
    league: 'MLN',
    notes: 'WEEK 12',
    games: [
      { label: 'BOKEH @ WORKING', time: '5:15 PM' },
      { label: 'BREWVO @ HOOD RATS', time: '6:00 PM' },
      { label: 'LEROYS @ DOCS', time: '6:45 PM' },
      { label: 'EPO @ KIPPLEES', time: '7:30 PM' },
    ],
  },
  {
    date: '08/207/2023',
    day: 'U',
    league: 'AA',
    notes: 'SUNDAY SPECIAL WEEK 7',
    games: [
      { label: 'Roca Bar @ Fidels', time: '5:15 PM' },
      { label: 'Golden Door @ Republic Services', time: '6:00 PM' },
      { label: 'Rick Winters @ Clover Club', time: '6:45 PM' },
      { label: 'Kennys @ Butcher Shoppe', time: '7:30 PM' },
    ],
  },
  {
    date: '08/208/2023',
    day: 'M',
    league: 'AAA',
    notes: 'WEEK 12',
    games: [
      { label: 'Solaris @ Waylons', time: '5:15 PM' },
      { label: 'Esthers @ River City', time: '6:00 PM' },
      { label: 'Schymiks @ Lucky lady', time: '6:45 PM' },
      { label: 'Penny Lane @ Deuces', time: '7:30 PM' },
    ],
  },
  {
    date: '08/209/2023',
    day: 'T',
    league: 'MLB',
    notes: 'WEEK 13',
    games: [
      { label: 'WORKING @ HOOD RATS', time: '5:15 PM' },
      { label: 'JSPH @ EPO', time: '6:00 PM' },
      { label: 'AAA @ 711', time: '6:45 PM' },
      { label: 'SAUCED @ BOKEH', time: '7:30 PM' },
    ],
  },
  {
    date: '09/05/2023',
    day: 'T',
    league: 'MLB',
    notes: 'WEEK 14',
    games: [
      { label: 'JSPH @ 711', time: '5:15 PM' },
      { label: 'DOCS @ AAA', time: '6:00 PM' },
      { label: 'SAUCED @ MAGIC JOHNSONS', time: '6:45 PM' },
      { label: 'ORIGINALS @ BREWVO', time: '7:30 PM' },
    ],
  },
  {
    date: '09/11/2023',
    day: 'M',
    league: 'AA',
    notes: 'PLAYOFFS!!!',
    games: [
      { label: '#4 @ #1', time: '5:15 PM' },
      { label: '#2 @ #3', time: '6:00 PM' },
      { label: 'CHAMPIONSHIP', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '09/12/2023',
    day: 'T',
    league: 'MLB',
    notes: 'WEEK 15',
    games: [
      { label: 'AAA @ EPO', time: '5:15 PM' },
      { label: '711 @ KIPPLEES', time: '6:00 PM' },
      { label: 'MAGIC JOHNSONS @ BOKEH', time: '6:45 PM' },
      { label: 'X', time: '7:30 PM' },
    ],
  },
  {
    date: '09/19/2023',
    day: 'T',
    league: 'MLB',
    notes: 'DECISION DAY WEEK 16!!',
    games: [
      { label: 'EPO @ LEROYS', time: '5:15 PM' },
      { label: '711 @ DOCS', time: '6:00 PM' },
      { label: 'JOHNSONS @ BREWVO', time: '6:45 PM' },
      { label: 'ORIGINALS @ BOKEH', time: '7:30 PM' },
    ],
  },
  {
    date: '09/25/2023',
    day: 'M',
    league: 'ALL',
    notes: 'MLB AND AAA PLAYOUTS',
    games: [
      { label: 'NL GAME', time: '5:15 PM' },
      { label: 'AL GAME', time: '6:00 PM' },
      { label: 'AAA GAME', time: '6:45 PM' },
      { label: 'MLB GAME', time: '7:30 PM' },
    ],
  },
  {
    date: '09/26/2023',
    day: 'T',
    league: 'MLB',
    notes: 'National Leauge Playoffs',
    games: [
      { label: '#5 @ #2', time: '5:15 PM' },
      { label: '#4 @ #3', time: '6:00 PM' },
      { label: 'Final', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '09/30/2023',
    day: 'S',
    league: 'ALL',
    notes: 'River City Wiffleball Classic',
    games: [
      { label: '', time: '5:15 PM' },
      { label: '', time: '6:00 PM' },
      { label: '', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '10/02/2023',
    day: 'M',
    league: 'AAA',
    notes: 'PLAYOFFS!!!',
    games: [
      { label: '#4 @ #1', time: '5:15 PM' },
      { label: '#3 @ #2', time: '6:00 PM' },
      { label: 'Championship', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '10/03/2023',
    day: 'T',
    league: 'MLB',
    notes: 'American League Playoffs',
    games: [
      { label: '#5 @ #2', time: '5:15 PM' },
      { label: '#4 @ #3', time: '6:00 PM' },
      { label: 'Final', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '10/10/2023',
    day: 'T',
    league: 'MLB',
    notes: 'HCWL CHAMPIONSHIP',
    games: [
      { label: 'American League Final', time: '5:15 PM' },
      { label: 'National League Final', time: '6:00 PM' },
      { label: 'Championship', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '10/17/2023',
    day: 'S',
    league: 'ALL',
    notes: 'WIFFLEBALL',
    games: [
      { label: 'BANQUET', time: '5:15 PM' },
      { label: '', time: '6:00 PM' },
      { label: '', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
  {
    date: '10/24/2023',
    day: 'S',
    league: 'ALL',
    notes: 'Evansville Wiffleball Championship',
    games: [
      { label: 'Semifinal', time: '5:15 PM' },
      { label: 'Semifinal', time: '6:00 PM' },
      { label: 'Championship', time: '6:45 PM' },
      { label: '', time: '7:30 PM' },
    ],
  },
];
