import { type SchemaTypeDefinition } from "sanity";
import { heroBanner } from "./components";
import { buttons } from "./modules";

import {
  aboutPage,
  artsPage,
  blogCategory,
  business,
  businessCategory,
  businessesPage,
  contactInfo,
  contactPage,
  event,
  eventsPage,
  feature,
  globalSettings,
  hcadaPage,
  headingBlock,
  homePage,
  iconItem,
  navMenu,
  person,
  post,
  project,
  projectCategory,
  social,
  svg,
  testimonial,
  volunteerPage,
} from "./doctypes";

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [
    aboutPage,
    artsPage,
    blogCategory,
    business,
    businessCategory,
    businessesPage,
    contactInfo,
    contactPage,
    event,
    eventsPage,
    feature,
    globalSettings,
    hcadaPage,
    headingBlock,
    homePage,
    iconItem,
    navMenu,
    person,
    post,
    project,
    projectCategory,
    social,
    svg,
    testimonial,
    volunteerPage,
    heroBanner,
    buttons,
  ],
};
